model:
  name: CNNModelV0
  num_classes: 9

training:
  epochs: 6
  verbose: True
  batch_size: 32
  learning_rate: 0.1
  hidden_features: 32
  out_features: 9
  kernel_size: 3
  stride: 1
  padding: 0
  seed: 42

save_model:
  model_name: FashionMNISTModel_V0